from llm import generate_response


def summarize_chunk(chunk):
    """
    Generate a study-focused summary for one text chunk.

    Parameters:
        chunk: A piece of cleaned study material.

    Returns:
        Summary generated by the local LLM.
    """

    prompt = f"""
You are an AI study assistant.

Summarize the following study material clearly and accurately.

Focus on:
- important concepts
- definitions
- key facts
- important relationships

Do not add information that is not present in the provided material.

Study material:

{chunk}
"""

    return generate_response(prompt)