from llm import generate_response


def summarize_chunk(chunk):
    """
    Generate a study-focused summary for one text chunk.

    Parameters:
        chunk: A piece of cleaned study material.

    Returns:
        Summary generated by the local LLM.
    """

    prompt = f"""
You are an AI study assistant.

Summarize the following study material clearly and accurately.

Focus on:
- important concepts
- definitions
- key facts
- important relationships

Do not add information that is not present in the provided material.

Study material:

{chunk}
"""

    return generate_response(prompt)


def create_final_summary(chunk_summaries):
    """
    Combine individual chunk summaries into one final study summary.

    Parameters:
        chunk_summaries: List of summaries generated from individual chunks.

    Returns:
        Final summary generated by the local LLM.
    """

    combined_summaries = "\n\n".join(
        f"Section {i + 1}:\n{summary}"
        for i, summary in enumerate(chunk_summaries)
    )

    prompt = f"""
You are an AI revision assistant.

Create a comprehensive final study summary from the section summaries below.

Requirements:
- Cover the most important concepts.
- Keep important definitions.
- Preserve important facts and relationships.
- Organize the information using clear headings and bullet points.
- Remove unnecessary repetition.
- Do not introduce information that is not present in the provided summaries.
- Make the result useful for exam revision.

Section summaries:

{combined_summaries}
"""

    return generate_response(prompt)